---
- name: Apache server installed
  hosts: node1
  become: yes

  tasks:

    - name: Install Apache with package
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - mod_ssl
    
    - name: Apache enabled and running
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true
    
    - name: Copy index.html from source files/web.html to /var/www/html/index.html
      ansible.builtin.copy:
        src: "files/web.html"
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: 420
    
    