---
- name: Apache server installed
  hosts: node1
  become: yes

  tasks:

    #- name: Install Apache with package

    #- name: Apache enabled and running
    
    #- name: Copy index.html from source files/web.html to /var/www/html/index.html
    