---
- name: Capture Setup
  hosts: node1

  tasks:

    #- name: Collect all facts and register in setup variable

    #- name: Show metadata variable using debug module

    #- name: gather_subset ansible ansible_eth0 and ansible_*_mb facts with setup and register myfacts variable
    
    #- name: Show myfacts variable using debug module